apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-api-v2
  labels:
    app: claims-api-v2
    mesh: istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claims-api
      version: "v2"
  template:
    metadata:
      labels:
        app: claims-api
        version: "v2"
    spec:
      containers:
      - name: claims-api
        image: "<ACR Name>.azurecr.io/claims-api:<Image Tag for v2>"
        imagePullPolicy: Always
        env:
        - name: ConnectionStrings__SqlServerDb
          value: "<Azure SQL Server Connection String>"
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v1/claims/healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /api/v1/claims/healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-api-v1
  labels:
    app: claims-api-v1
    mesh: istio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: claims-api
      version: "v1"
  template:
    metadata:
      labels:
        app: claims-api
        version: "v1"
    spec:
      containers:
      - name: claims-api
        image: "<ACR Name>.azurecr.io/claims-api:<Image Tag for v1>"
        imagePullPolicy: Always
        env:
        - name: ConnectionStrings__SqlServerDb
          value: "<Azure SQL Server Connection String>"
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v1/claims/healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /api/v1/claims/healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: claims-api
  labels:
    app: claims-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: claims-api
