apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: claims-api-podid
spec:
  type: 0
  resourceID: /subscriptions/0000-0000/resourcegroups/resourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/claims-api-mid
  clientID: 00000-7d73-470b-9c28-0000
